export type DailyEntryRow = {
  id: string;
  planilha_id: string;
  data: string;
  investimento: number;
  faturamento_principal: number;
  vendas_principal: number;
  ob1_faturado: number;
  ob1_vendas: number;
  ob2_faturado: number;
  ob2_vendas: number;
  ob3_faturado: number;
  ob3_vendas: number;
  ob4_faturado: number;
  ob4_vendas: number;
  ob5_faturado: number;
  ob5_vendas: number;
  upsell_faturado: number;
  upsell_vendas: number;
  downsell_faturado: number;
  downsell_vendas: number;
  ctr: number;
  page_view: number;
  carregamento: number;
  initiate_checkout: number;
  cpm: number;
  created_at: string;
  updated_at: string;
};

export type DailyEntryInsert = {
  id?: string;
  planilha_id: string;
  data: string;
  investimento?: number;
  faturamento_principal?: number;
  vendas_principal?: number;
  ob1_faturado?: number;
  ob1_vendas?: number;
  ob2_faturado?: number;
  ob2_vendas?: number;
  ob3_faturado?: number;
  ob3_vendas?: number;
  ob4_faturado?: number;
  ob4_vendas?: number;
  ob5_faturado?: number;
  ob5_vendas?: number;
  upsell_faturado?: number;
  upsell_vendas?: number;
  downsell_faturado?: number;
  downsell_vendas?: number;
  ctr?: number;
  page_view?: number;
  carregamento?: number;
  initiate_checkout?: number;
  cpm?: number;
  created_at?: string;
  updated_at?: string;
};

export type DailyEntryUpdate = Partial<DailyEntryInsert>;
